# Author: Daniel Gisolfi
# 2019-09-20

version: '2'
services:
  api:
    image: api
    restart:  unless-stopped
    container_name: war-api
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}:/server"